# Cooldown bypass permission : brtp.bypass
################################################
# Teleportation cooldown (in seconds)
cooldown: 3600
# Min-size teleportation radius
min: 300
# Max-size teleportation radius
coord:
  x: 3500
  z: 3500
# Safe-tp will prevent players to be teleported in any liquid
safe-tp: true
#################################################
messages:
  # Available placeholder(s) :  %CoordX%, %CoordY%, %CoordZ%
  # Send a message after the player was randomly teleported
  successtp: "&aYou were succesfuly randomly teleported to &2X : %CoordX%&a, &2Y : %CoordY%&a, &2Z : %CoordZ%"
  # Available placeholder(s) : %hours%, %minutes%, %seconds%
  # Send a message when the player is still in cooldown
  oncooldown: "&cRetry in &4%hours% &chour(s), &4%minutes% &cminute(s), &4%seconds% &cseconde(s)"
  # Available placeholder(s) : %player%
  # Send a message when the command is misspelled
  wrongsyntax: "&c%player% you should try /randomteleport"