name: BetterRandomTeleport
version: 1.1.0
api-version: 1.13
author: Corazun
description: BetterRandomTeleport, try /rtp or /randomteleport
main: fr.corazun.brtp.Main
commands:
  randomteleport:
    description: Randomly teleport the player through the map
    permission: brtp.use
    aliases: [rtp]
  betterrandomteleport:
    description: Related plugin configuration commands
    permission: brtp.configuration
    aliases: [brtp]
permissions:
  brtp.bypass:
    description: Give the ability to bypass the rtp cooldown
    default: op
  brtp.everywhere:
    description: Give the ability to bypass the random teleport restriction on disabled world(s)
    default: op
